---
version: 2.1

commands:
  pre:
    steps:
      - run: node --version
      - run: npm --version
      - run: yarn --version
      - run: openssl version
      - checkout

  install:
    steps:
      - run:
          name: Install Pebble
          command: /bin/bash ./scripts/test-suite-install-pebble.sh

      - run:
          name: Start Pebble Challenge Test Server
          command: /tmp/pebble-challtestsrv -dns01 ":8053" -tlsalpn01 ":5001" -http01 ":5002" -https01 ":5003" -defaultIPv4 "127.0.0.1" -defaultIPv6 ""
          background: true

      - run:
          name: Start Pebble
          command: /tmp/pebble -strict -config /tmp/pebble.json -dnsserver "127.0.0.1:8053"
          background: true

      - run:
          name: Wait for Pebble
          command: /bin/bash ./scripts/test-suite-wait-for-pebble.sh

  test:
    steps:
      - run: yarn

      - run:
          command: yarn run test
          environment:
            NODE_EXTRA_CA_CERTS: /tmp/ca.cert.pem
            ACME_DIRECTORY_URL: https://127.0.0.1:14000/dir
            ACME_CHALLTESTSRV_URL: http://127.0.0.1:8055
            ACME_DNS_RESOLVER: 127.0.0.1:8053
            ACME_TLSALPN_PORT: 5001
            ACME_HTTP_PORT: 5002
            ACME_HTTPS_PORT: 5003

jobs:
  v8: { docker: [{ image: circleci/node:8 }], steps: [ pre, install, test ]}
  v10: { docker: [{ image: circleci/node:10 }], steps: [ pre, install, test ]}
  v12: { docker: [{ image: circleci/node:12 }], steps: [ pre, install, test ]}

workflows:
  test-suite:
    jobs:
      - v8
      - v10
      - v12
